# Generated by Django 3.1 on 2020-08-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='menuler',
            name='adi',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='menuler',
            name='menu_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='menuler',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modmain.menuler'),
        ),
        migrations.AddField(
            model_name='menuler',
            name='sira',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuler',
            name='viewId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modmain.defined_views'),
        ),
    ]
