# Generated by Django 3.1 on 2020-08-31 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modmain', '0003_user_menu_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_menu_permission',
            name='permissionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modmain.defined_permissions'),
        ),
    ]
